### ISSUE TITLE
[Task] Membuat pembungkus kartu ucapan

### ISSUE THREAD

**Issue by egasa21** [egasa21/ppl-project#10]

**Comment by AKBARFEBRIANAMAR** [comment]
https://drive.google.com/drive/folders/1jxGy1wsiwoIbpyAeocLBR6vPSRFchXYv

**Comment by barrxyz** [comment]
https://drive.google.com/drive/folders/1jxGy1wsiwoIbpyAeocLBR6vPSRFchXYv

**Comment by egasa21** [comment]
Sudah good ini
