### ISSUE TITLE
[Task] Menentukan anggaran proyek

### ISSUE THREAD

**Issue by egasa21** [egasa21/ppl-project#3]
**Anggaran Proyek Kartu Ucapan Wisuda:**
**1. Bahan Baku:**
Kertas kualitas baik: Rp 10.000
Tinta printer: Rp 5000
Stiker atau hiasan tambahan: Rp 5000

**2. Biaya Pencetakan (5 kartu x Biaya per kartu):**
Rp 15.000

**3. Alat dan Peralatan:**
Penggunaan printer: Tidak diperlukan
Gunting atau cutter: Gratis (jika sudah punya)
Meja kerja: Gratis (jika sudah punya)

**4. Tenaga Kerja:**
Waktu produksi: Gratis (dilakukan sendiri)

**Total Anggaran: Rp 35.000**

**Comment by oksaregina** [comment]
**Anggaran Proyek Kartu Ucapan Wisuda:**
**1. Bahan Baku:**
Kertas kualitas baik: 10 ribu
Tinta printer: 5 ribu
Stiker atau hiasan tambahan: 5 ribu

**2. Biaya Pencetakan (5 kartu x Biaya per kartu):*
15 ribu

**3. Alat dan Peralatan:**
Penggunaan printer: Tidak diperlukan
Gunting atau cutter: Gratis (jika sudah punya)
Meja kerja: Gratis (jika sudah punya)

**4. Tenaga Kerja:**
Waktu produksi: Gratis (dilakukan sendiri)

**5. Biaya Lainnya:**
Listrik dan air: 2 ribu
Transportasi (opsional): 3 ribu
Total Anggaran: 40 ribu

**Comment by egasa21** [comment]
Biaya listrik sama transport keknya ga perlu

**Comment by oksaregina** [comment]
ohh iya, kalo yg lainnya gmna?

**Comment by egasa21** [comment]
Aman
