### ISSUE TITLE
[Task] Menentukan peran dan tanggung jawab tim proyek, merekrut anggota tim proyek

### ISSUE THREAD

**Issue by egasa21** [egasa21/ppl-project#5]
Anggota tim : 

1. Ega Saputra : Product Owner
2. Anisa Nurohmah : Scrum Master
3. Sania Wati : Dev Team
4. Akbar Febrian Amar : Dev Team
5.  Alex Arif Setiawan : Dev Team
6. Regina Oksa : Dev Team

**Comment by egasa21** [comment]
regina ketingalan wkwk

**Comment by oksaregina** [comment]
parah si
