### ISSUE TITLE
[Task] Identifikasi fitur dan fungsi produk

### ISSUE THREAD

**Issue by egasa21** [egasa21/ppl-project#6]
Fitur : 
1.  Ucapan Selamat
2. Doa
3. Keterangan

Fungsi :
1.  Sebagai bentuk apresiasi
2. Swbagai ucapan selamat
3. Sebagai kenang kenangan

**Comment by egasa21** [comment]
@AlexArif02 Cari orang buat di wawancara, kumpulin datanya. Abis itu dipake buat identifikasi fitur sama fungsi

**Comment by egasa21** [comment]
Taruh link drive wawancaranya disi lek @AlexArif02

**Comment by AlexArif02** [comment]
https://drive.google.com/drive/folders/1UimXcOCpgNlETtd94u0nDKhgBT8dMtip
