### ISSUE TITLE
[Task] Desain kartu ucapan

### ISSUE THREAD

**Issue by egasa21** [egasa21/ppl-project#7]
Buatkan desain untuk kartu ucapan. Desain terdiri dari desain kartu dan pembungkus kartu ucapan

**Comment by oksaregina** [comment]
Link desain pembungkusan (amplop): https://drive.google.com/drive/folders/1mYU-EZ48ObZP1nkhOuRBlHVGO1VNR4fE?usp=drive_link

**Comment by Sania-07** [comment]
Link Desain Kartu Ucapan: 
https://www.canva.com/design/DAF4WGbaLss/amz4VPfGaMyAKi2LmDTJPg/edit?utm_content=DAF4WGbaLss&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by egasa21** [comment]
Oke good

**Comment by Sania-07** [comment]
Oke
