### ISSUE TITLE
[Task] Menentukan bahan kertas kartu ucapan

### ISSUE THREAD

**Issue by egasa21** [egasa21/ppl-project#8]
Cari beberapa referensi kertas yang biasa dipake untuk pembuatan kartu ucapan.

**Comment by AKBARFEBRIANAMAR** [comment]
Menggunakan kertas Art Carton / Ivory 230gsm

**Comment by egasa21** [comment]
Kalo pake 310 ketebelan ngga bar @barrxyz ?

**Comment by AKBARFEBRIANAMAR** [comment]
ga terlalu, tapi dah pas kok

**Comment by barrxyz** [comment]
> Kalo pake 310 ketebelan ngga bar [@barrxyz](https://github.com/barrxyz) ?
